name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install
      run: npm clean-install
    - name: Verify
      run: |
        npm run prepare
        # Fail if "npm run prepare" generated new changes in dist
        git update-index --refresh dist/* && git diff-index --quiet HEAD dist
    - name: Lint
      run: npm run all

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        version:
        #- 'latest'
        #- 'v0.3.20'
        - '0.3.20'
        #- '0.3'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup konjure
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: No boom
      if: ${{ matrix.version != 'latest' }}
      run: |
        konjure --version | grep ${{ matrix.version }}
