name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install
      run: npm clean-install
    - name: Verify
      run: |
        npm run prepare
        # Fail if "npm run prepare" generated new changes in dist
        git update-index --refresh dist/* && git diff-index --quiet HEAD dist
    - name: Lint
      run: npm run all

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        version:
        - 'latest'
        - 'v0.4.6'
        - '0.4.6'
        - '0.4'
        # Skip macOS builds that would require GitHub API access
        exclude:
        - os: macos-latest
          version: 'latest'
        - os: macos-latest
          version: '0.4'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup konjure
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: No boom
      run: konjure --version
